#!/usr/bin/env python3
"""
ChArUco calibration for camera_sensor_fusion, matching the board generated by:

  board = cv2.aruco.CharucoBoard((10,7), 0.03, 0.022, DICT_4X4_50)

IMPORTANT: --square-mm and --marker-mm below MUST match your PRINTED board,
not the values used to generate the image. Printers often scale to fit the
page. Measure one black square edge-to-edge with a ruler before running
`solve`, and use that real measurement.

Usage:

  # Step 1: capture frames of the physical board (headless-friendly)
  python3 calibrate_charuco.py capture \
      --device 0 --width 1920 --height 1080 \
      --out calib/front_charuco_frames --count 20 --interval 2.0

  Move the board to different angles/distances/positions in the frame while
  this runs -- it auto-captures every --interval seconds, no keypress needed.

  A live preview streams at http://<PI_IP>:8092/preview.mjpg while capturing
  -- open it in VLC from your desktop (Media -> Open Network Stream) to watch
  in real time, with a live sharpness score and countdown to the next shot
  overlaid. Green/"OK" means the frame is sharp enough; red/"BLURRY" means
  hold still longer before the next shot fires. Pass --no-preview to disable.

  # Step 2: solve calibration from the captured frames
  python3 calibrate_charuco.py solve \
      --frames-dir calib/front_charuco_frames \
      --squares-x 10 --squares-y 7 \
      --square-mm 30 --marker-mm 22 \
      --out calib/gs_front_1920x1080.yml

  Prints RMS reprojection error at the end -- under 0.5px good, under 1.0px
  usable, above that retake with more angle/distance variety.
"""
import argparse
import glob
import http.server
import os
import socketserver
import threading
import time

import cv2
import numpy as np


def make_board(squares_x, squares_y, square_mm, marker_mm):
    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    board = cv2.aruco.CharucoBoard(
        (squares_x, squares_y),
        square_mm / 1000.0,
        marker_mm / 1000.0,
        dictionary,
    )
    return board, dictionary


def sharpness_score(frame):
    """Laplacian variance -- higher is sharper. Rough guide for this camera:
    under ~100 is soft/blurry, 200+ is generally usable."""
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    return cv2.Laplacian(gray, cv2.CV_64F).var()


_latest_jpeg = None
_latest_frame = None
_latest_lock = threading.Lock()
_stop_grabbing = threading.Event()


class _PreviewHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path != "/preview.mjpg":
            self.send_response(404)
            self.end_headers()
            return
        self.send_response(200)
        self.send_header("Content-Type", "multipart/x-mixed-replace; boundary=frame")
        self.end_headers()
        try:
            while True:
                with _latest_lock:
                    jpeg = _latest_jpeg
                if jpeg is None:
                    time.sleep(0.05)
                    continue
                self.wfile.write(b"--frame\r\n")
                self.wfile.write(b"Content-Type: image/jpeg\r\n")
                self.wfile.write(f"Content-Length: {len(jpeg)}\r\n\r\n".encode())
                self.wfile.write(jpeg)
                self.wfile.write(b"\r\n")
                time.sleep(0.03)
        except (BrokenPipeError, ConnectionResetError):
            pass

    def log_message(self, fmt, *args):
        pass  # quiet


def _run_preview_server(port):
    with socketserver.ThreadingTCPServer(("0.0.0.0", port), _PreviewHandler) as httpd:
        httpd.serve_forever()


def _grab_loop(cap, status_text_fn):
    """Runs in a background thread: continuously reads frames, keeps the
    latest raw frame available for saving, and updates the live preview
    with a sharpness overlay + whatever status text the caller provides."""
    global _latest_jpeg, _latest_frame
    while not _stop_grabbing.is_set():
        ok, frame = cap.read()
        if not ok:
            time.sleep(0.05)
            continue

        score = sharpness_score(frame)
        with _latest_lock:
            _latest_frame = (frame, score)

        color = (0, 255, 0) if score > 200 else (0, 0, 255)
        annotated = frame.copy()
        cv2.putText(annotated, f"sharpness={score:.0f} ({'OK' if score > 200 else 'BLURRY'})",
                    (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)
        cv2.putText(annotated, status_text_fn(), (20, 75),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)
        ok_enc, buf = cv2.imencode(".jpg", annotated, [cv2.IMWRITE_JPEG_QUALITY, 80])
        if ok_enc:
            with _latest_lock:
                _latest_jpeg = buf.tobytes()


def cmd_capture(args):
    global _latest_frame
    os.makedirs(args.out, exist_ok=True)
    cap = cv2.VideoCapture(args.device)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, args.width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, args.height)

    if not cap.isOpened():
        raise SystemExit(f"Could not open camera device {args.device}")

    actual_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    actual_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    saved = 0

    if not args.no_preview:
        t = threading.Thread(target=_run_preview_server, args=(args.preview_port,), daemon=True)
        t.start()
        print(f"Live preview: http://0.0.0.0:{args.preview_port}/preview.mjpg "
              f"(open in VLC from your desktop)")

    print(f"Capturing at {actual_w}x{actual_h}.")

    if args.manual:
        status_fn = lambda: f"MANUAL -- press Enter in this terminal to save [{saved}/{args.count}], q+Enter to stop"
        grab_thread = threading.Thread(target=_grab_loop, args=(cap, status_fn), daemon=True)
        grab_thread.start()
        time.sleep(0.5)  # let the first frame arrive before prompting

        print("Manual mode: position the board, watch the preview, then press Enter to save "
              "each shot. Type q then Enter to stop early.")
        while saved < args.count:
            user_in = input(f"[{saved}/{args.count}] Press Enter to capture (q to stop): ")
            if user_in.strip().lower() == "q":
                break
            with _latest_lock:
                if _latest_frame is None:
                    print("  No frame available yet, try again.")
                    continue
                frame, score = _latest_frame
            path = os.path.join(args.out, f"charuco_{saved:03d}.jpg")
            cv2.imwrite(path, frame)
            print(f"  saved {path}  sharpness={score:.0f} "
                  f"({'OK' if score > 200 else 'LIKELY BLURRY -- consider retaking this one'})")
            saved += 1

        _stop_grabbing.set()
        grab_thread.join(timeout=2)

    else:
        print("Move the ChArUco board around between shots (different angles, distances, "
              "positions in frame). Hold it fully still for a moment right before each shot "
              "to avoid blur.")
        next_shot = time.time()
        while saved < args.count:
            ok, frame = cap.read()
            if not ok:
                print("Warning: frame grab failed, retrying...")
                time.sleep(0.1)
                continue

            now = time.time()
            seconds_left = max(0.0, next_shot - now)

            if not args.no_preview:
                score = sharpness_score(frame)
                label = f"sharpness={score:.0f} ({'OK' if score > 200 else 'BLURRY'})  next shot in {seconds_left:.1f}s  [{saved}/{args.count}]"
                color = (0, 255, 0) if score > 200 else (0, 0, 255)
                annotated = frame.copy()
                cv2.putText(annotated, label, (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)
                ok_enc, buf = cv2.imencode(".jpg", annotated, [cv2.IMWRITE_JPEG_QUALITY, 80])
                if ok_enc:
                    with _latest_lock:
                        _latest_jpeg = buf.tobytes()

            if now >= next_shot:
                path = os.path.join(args.out, f"charuco_{saved:03d}.jpg")
                cv2.imwrite(path, frame)
                score = sharpness_score(frame)
                print(f"[{saved + 1}/{args.count}] saved {path}  sharpness={score:.0f} "
                      f"({'OK' if score > 200 else 'LIKELY BLURRY -- consider retaking this one'})")
                saved += 1
                next_shot = now + args.interval

    cap.release()
    print(f"Done. {saved} frames saved to {args.out}")


def cmd_solve(args):
    board, dictionary = make_board(args.squares_x, args.squares_y, args.square_mm, args.marker_mm)
    detector_params = cv2.aruco.DetectorParameters()
    charuco_params = cv2.aruco.CharucoParameters()
    charuco_detector = cv2.aruco.CharucoDetector(board, charuco_params, detector_params)

    files = sorted(glob.glob(os.path.join(args.frames_dir, "*.jpg")) +
                    glob.glob(os.path.join(args.frames_dir, "*.png")))
    if not files:
        raise SystemExit(f"No images found in {args.frames_dir}")

    all_obj_points = []
    all_img_points = []
    image_size = None
    used = 0

    for f in files:
        img = cv2.imread(f)
        if image_size is None:
            image_size = (img.shape[1], img.shape[0])  # (w, h)

        charuco_corners, charuco_ids, marker_corners, marker_ids = charuco_detector.detectBoard(img)

        if charuco_corners is None or charuco_ids is None or len(charuco_ids) < 6:
            print(f"  not enough corners in {os.path.basename(f)} (skipped)")
            continue

        obj_points, img_points = board.matchImagePoints(charuco_corners, charuco_ids)
        if obj_points is None or len(obj_points) < 6:
            print(f"  match failed in {os.path.basename(f)} (skipped)")
            continue

        all_obj_points.append(obj_points)
        all_img_points.append(img_points)
        used += 1
        print(f"  found {len(charuco_ids)} charuco corners in {os.path.basename(f)}")

    if used < 8:
        print(f"WARNING: only {used} usable frames. 15-20+ recommended for a stable result.")
    if used == 0:
        raise SystemExit("No usable frames -- check --squares-x/--squares-y match your board, "
                          "and that it was well-lit, in focus, and mostly in frame.")

    rms, K, dist, rvecs, tvecs = cv2.calibrateCamera(
        all_obj_points, all_img_points, image_size, None, None
    )

    print(f"\nCalibration solved using {used} frames.")
    print(f"RMS reprojection error: {rms:.4f} px "
          f"({'good' if rms < 0.5 else 'usable' if rms < 1.0 else 'HIGH -- consider retaking frames'})")
    print(f"Camera matrix:\n{K}")
    print(f"Distortion coeffs:\n{dist}")

    write_opencv_yaml(args.out, image_size[0], image_size[1], K, dist)
    print(f"\nSaved calibration to {args.out}")


def write_opencv_yaml(path, width, height, K, dist):
    fs = cv2.FileStorage(path, cv2.FILE_STORAGE_WRITE)
    fs.write("image_width", width)
    fs.write("image_height", height)
    fs.write("camera_matrix", K)
    fs.write("dist_coeffs", dist)
    fs.release()


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_cap = sub.add_parser("capture", help="Capture ChArUco board frames from the camera")
    p_cap.add_argument("--device", type=int, default=0)
    p_cap.add_argument("--width", type=int, default=1920)
    p_cap.add_argument("--height", type=int, default=1080)
    p_cap.add_argument("--out", default="calib/charuco_frames")
    p_cap.add_argument("--count", type=int, default=20)
    p_cap.add_argument("--interval", type=float, default=2.0)
    p_cap.add_argument("--preview-port", type=int, default=8092)
    p_cap.add_argument("--no-preview", action="store_true",
                        help="Disable the live MJPEG preview server")
    p_cap.add_argument("--manual", action="store_true",
                        help="Wait for Enter keypress to save each shot instead of an automatic timer")
    p_cap.set_defaults(func=cmd_capture)

    p_solve = sub.add_parser("solve", help="Solve calibration from captured frames")
    p_solve.add_argument("--frames-dir", required=True)
    p_solve.add_argument("--squares-x", type=int, default=10)
    p_solve.add_argument("--squares-y", type=int, default=7)
    p_solve.add_argument("--square-mm", type=float, required=True,
                          help="MEASURED square edge length in mm -- from the physical printout, not the generator script")
    p_solve.add_argument("--marker-mm", type=float, required=True,
                          help="MEASURED marker edge length in mm -- from the physical printout")
    p_solve.add_argument("--out", required=True)
    p_solve.set_defaults(func=cmd_solve)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
